root: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

env:
  es2021: true
  browser: true

extends:
  - 'airbnb-base'

rules:
  no-console: 'off'
  import/extensions: 'off'
  no-param-reassign:
    - 'error'
    - ignorePropertyModificationsFor:
        - 'state'
        - 'elements'
  no-underscore-dangle:
    - 'error'
    - allow: ['__dirname']
